repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Specify a tag or sha
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 23.11.0  # Specify a tag or sha
    hooks:
      - id: black
